/*
  보호는 시작했는데, 입양은 가지 않았다면 -> IN에는 있지만 OUT에는 없는 것을 찾으면 된다.
  LEFT OUTER JOIN을 해서, OUT의 DATETIME이 NULL인 동물 찾기
*/
SELECT AI.NAME, AI.DATETIME
FROM ANIMAL_INS AI LEFT OUTER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AO.DATETIME IS NULL
ORDER BY AI.DATETIME
LIMIT 3
