/*
  JOIN -> 2개의 테이블을 합치는 것
  FROM 절에서 2개의 테이블에 어떤 조인을 할 것인지, 어떤 조인 조건인지 명시
  (JOIN 사진 : https://velog.io/@pm1100tm/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-SQL-SELECT-%EC%97%86%EC%96%B4%EC%A7%84-%EA%B8%B0%EB%A1%9D-%EC%B0%BE%EA%B8%B0)
*/
SELECT AO.ANIMAL_ID, AO.NAME 
FROM ANIMAL_OUTS AO LEFT OUTER JOIN ANIMAL_INS AI ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL
ORDER BY AO.ANIMAL_ID
