/*
  JOIN 이용하여 2개의 테이불 묶어서 DATETIME 비교하여 출력
*/
SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AI INNER JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME
